codepod-io/codepod

ui/src/components/repo/graph.js
Avoid passing `setNodes` and `onRize` functions when rendering nodes, which helps fix bugs when sync the nodes' info between users.
=> Fix: Simplify the code to resize a node

ui/src/components/Canvas.tsx, ui/src/components/Sidebar.tsx, ui/src/lib/fetch.tsx, ui/src/lib/store.tsx, ui/src/pages/repo.tsx
Previously the frontend used two methods to access backend GraphQL APIs:
1. through apollo client as a React context
2. through manually calling fetch() with server URL
Now we removed the second kind of API calls, and consistently use the apollo client everywhere.
=> use the React Component apollo client in fetch.ts

ui/src/components/Canvas.tsx, ui/src/components/MyMonaco.tsx, ui/src/lib/runtime.tsx
Now output is on a new panel to the right of the editor by default. Can toggle between right/bottom.
=> Better output layout

ui/src/components/Canvas.tsx, ui/src/components/MyMonaco.tsx, ui/src/lib/nodes.tsx, ui/src/lib/store.tsx
Change
1. Use lazy eval function instead of accessing pods directly. So the components using pod/pods will not re-render when any value changes in pods.
2. Memorize `MyMonaco` component with only `id` and `gitvalue` property. Prevent force rendering from parent components.
3. Clean up auto layout function for `codeNode`.
The following work later if available:
1. `ResultBlock` will be re-rendered when its parent `codeNode` was dragged. I think we can also memo it and set the execution number like out[num] in (https://github.com/codepod-io/codepod/issues/55) as a prop to force re-rendering it only when the result changes. I just remained it as origin, please consider combining this issue when implementing the execution number.
close https://github.com/codepod-io/codepod/issues/51
=> Fix: Unnecessary Re-rendering

compose/dev/nginx.conf, ui/src/components/Canvas.tsx, ui/src/components/MyMonaco.tsx, ui/src/components/Toolbox.tsx, ui/src/components/canvas.style.js, ui/src/lib/store.tsx
1. top toolbar
2. editor hightlight
3. implement delete btn
=> core: ui refactor

ui/src/components/Canvas.tsx, ui/src/components/Toolbox.tsx
issue [67](https://github.com/codepod-io/codepod/issues/67)
=> feat: add button to control output

ui/src/components/Canvas.tsx, ui/src/lib/nodes.tsx, ui/src/lib/store.tsx
1. fix the previous bug on computing the absolute position of nested scopes
2. sort the nodes so that nodes of a higher level always appear on top (close #63)
=> fix: dropping into nested scope

api/src/resolver_repo.ts, ui/src/components/ShareProjDialog.tsx, ui/src/lib/fetch.tsx, ui/src/lib/me.tsx, ui/src/lib/parser.tsx, ui/src/lib/store.tsx, ui/src/pages/repo.tsx, ui/src/pages/repos/CreateRepoForm.tsx, ui/src/pages/repos/index.tsx
1. When you haven't logged in, show the error message and auto redirect to login page:
2. When you access a repo that you are not supposed to be there (e.g., a private repo where you are neither an author or collaborator, or a wrong URL), show the error message and auto redirect to your dashboard page.
3. Fix the load path issue in parser, otherwise, a user can't enter a repo by URL directly. Thanks to @lihebi , but it doesn't promise the parser ready for analyzing code when you directly jump to a repo by URL. We may modify more code to support waiting for the loading in the future.
4. Fix the bug that a public repo can't be created. （But I think the UI can be improved, it looks a little misleading)
5. Change the notification in share project dialog into toast style, which is auto hidden …
=> Fix: auth error auto redirect & tree-sitter load path & toast notification

ui/src/pages/repos/index.tsx
In the following code, we should not change the local `loading` state in a child component, as that will trigger a re-render of the parent component.
https://github.com/codepod-io/codepod/blob/c3d457f5f44d6fc53435b0a6029421fa50ee1c69/ui/src/pages/repos/index.tsx#L332-L336
As a result, there was a warning:
This PR fixes it.
=> fix setloading recursive rendering issue

ui/src/components/Canvas.tsx, ui/src/lib/runtime.tsx
There are two ways to run code: click the toolbar button and shift-enter keyboard shortcut. This PR put `analyzeCode` into wsRun action so that both ways behave consistently.
=> move analyzeCode logic into wsRun

api/src/resolver_repo.ts, api/src/typedefs.ts, ui/src/components/Canvas.tsx, ui/src/components/CanvasContextMenu.tsx, ui/src/components/MyMonaco.tsx, ui/src/components/Sidebar.tsx, ui/src/lib/fetch.tsx, ui/src/lib/store.tsx
For a public repo, even an anonymous user can read everything in it, but only the owner and collaborators are allowed to edit. In this PR: we further distinguish the access for different roles in a repo, enforced the access rule both on the front-end and back-end side. 
- front-end: hide operation UI for guests, including auto saving button, runtime kernel in the sidebar, new code/scope menu
- back-end: prohibit mutate query when auth fails
Besides, remove the awareness info (remote cursor/selection) of guests, only show the operation update from an owner/collaborator. A guest can never edit/run code in the pod or drag a pod.
Now, a public repo can also be shared with collaborators.
TODO
=> Fix: read/write access control for public repos

ui/src/App.tsx, ui/src/components/Header.tsx, ui/src/components/Sidebar.tsx, ui/src/hooks/useLocalStorage.ts, ui/src/pages/repo.tsx
closes #75 
- Add Breadcrumb for repo page, dashboard page and profile page
- Foldable sidebar
- I have pushed `Docs` to the right side! (let me know if you don't like it)
- the position of Expand `>` button is weird
- Have a standalone HomePage
- Automatically redirect logged-in user from `/` to `/repos`
- Only `/repos` shows the "Dashboard" breadcrumb
***Note:***
In the original issue, the request is `Codepod/{USERNAME}'s Profile`
But I think it's duplicate information. So let's use `CodePod / Profile` 😄 
- Prettier IDE integration?
- Windows developer might need some fix for file-watching
```js
// ui/config-overrides.js
config.watchOptions = {
ignored: /node_modules/,
poll: true,
};
```
=> feat: header and sidebar improvement

ui/src/components/Canvas.tsx, ui/src/components/MyMonaco.tsx, ui/src/components/Sidebar.tsx, ui/src/lib/fetch.tsx, ui/src/lib/nodes.tsx, ui/src/lib/store.tsx, ui/src/lib/utils.tsx
1. **Fix several node initialization issues**: specify custom drag handle, check init state after the provider synced, specify width when adding pod to the db, etc.
2. **Enforce write access control for guests**: hide the interactivity button (lock) globally, disable the resize box, and discard any node info update to the `yjs` servers from a guest. In this early stage, a user may feel a little inconvenient to select text in a pod without the button, however, they can fix the viewpoint by pressing <kbd>Control</kbd> temporarily. We (@lihebi ) will implement some other robust method to add auth layer to the yjs servers and fix the viewpoint automatically in the future if we have time.
3. **Sync code pod resize in real-time**: rewrite the logic of resetting the pod width, which makes all …
=> Fix: Lock interactivity & sync width resize & improve render performance

ui/src/components/MyMonaco.tsx
So that `shift-enter` triggers the focused editor. This was accidentally removed in the previous commit.
=> fix: add back setCurrentEditor

ui/src/components/Canvas.tsx, ui/src/lib/nodes.tsx, ui/src/lib/store.tsx
Separate the pod `selected` states for each user, stop synchronizing all node data by remote YMap. Maintain `pod[id].selected` in local and apply their states every time after pulling updates from the remote yjs server.
Change the implementation to support multi-selection in a <kbd>Ctrl</kbd> way: keep pressing <kbd>Ctrl</kbd> and click on the drag handle of several pods, then you can drag or delete all of them at once, like what we do on a Windows desktop when selecting multiple files.
close https://github.com/codepod-io/codepod/issues/112
Known issues:
1. A guest user cannot select any pod now. It is fine so far. I will fix it when implementing the clipboard to enable copy a bunch of pods from a read-only repo and then paste them into another repo where they are allowed to write.
2. If …
=> Fix: Support Multi-selection in `ctrl` way

ui/src/components/Canvas.tsx, ui/src/lib/store.tsx
closes #97
long text will become an ellipsis.
We can further improve some of the controlling behaviors around this name input field. (hint, style, arrow key navigation)
=> feat: support naming on pod and scope

ui/src/components/Canvas.tsx, ui/src/lib/fetch.tsx, ui/src/lib/store.tsx
1. Replace the creation-order number with execution-order number (`pod[id].result.count`) in the top-left corner of a `codeNode`
2. Fix the useless scroll issue in result blocks (at least works on my Chrome on Win10)
=> Fix: remove output indices and horizontal scroll bar in result blocks

ui/src/components/Canvas.tsx
setPodName caused sync on page refresh. This PR fixes it.
=> don't set name on start when data.name is undefined

api/src/resolver.ts, api/src/resolver_runtime.ts, api/src/spawner-docker.ts, api/src/spawner-k8s.ts, api/src/typedefs.ts, proxy/src/node-proxy.ts, ui/src/components/Sidebar.tsx, ui/src/lib/runtime.tsx, ui/src/lib/utils.tsx, ui/src/pages/repos/index.tsx
Add two timers for runtime:
- **last active time**: this is the last time a runtime session is **connected**. The runtime **will be terminated** 12h after the last active time. Opening the repo (and connecting the runtime) will refresh the last active record.
- **up time**: the is when the runtime is **started**
On the dashboard, show the runtime's **last active time** for each repo.
On the repo canvas page, the sidebar shows the **up time**.
=> feat: add docker runtime TTL; better runtime connection & feedback

ui/src/components/Canvas.tsx, ui/src/components/MyMonaco.tsx, ui/src/lib/nodes.tsx, ui/src/lib/store.tsx
1. Fix the multi-selection hotkey issue for Mac users: Mac users can press `meta` key to multi-select nodes as what `ctrl` does for other users
2. Highlight the border in a darker blue than focused when selected.  Un-selection logic is also fixed
3. Apply the "same-parent rule": when a user selects more than one node in either `ctrl` or `shift` way, it checks if all selected nodes are of the same parent, otherwise, it will be difficult to drag them into the same scope or delete/cut them together. If the rule is violated when a new node is selected, we **un-select all previously selected nodes** and select only the new one.
4. Multiple pods can be dragged into a scope at once when selected: when dragging more than one node and the target is a scope, all selected nodes are dropped into the …
=> Fix: multi-selection with the same-parent rule & drop multiple pods into a scope at once

ui/src/components/Canvas.tsx, ui/src/lib/store.tsx
I don't know what triggered such a horrible code reformation in `canvas`, actually this is just a very tiny modification. Eventually, I adopted another simpler optimization strategy other than [what I proposed here](https://github.com/codepod-io/codepod/pull/136#discussion_r1045877268).  Please test it carefully before merging, it works on my side, but I'm not sure if any issue exists.
A brief summary:
1. Make all tooltips not draggable.
2. Rewrite `store.setPodPosition` and `store.setPodParent`, add a parameter `dirty: bool`, set `pod.dirty = pod.dirty | dirty`, that is, only triggers remote update request when the argument `dirty=true`. Note that we use `|` (or) operation instead of `=` (assign) to avoid a dirty pod cleaned by another local `setPodPosition` or `setPodParent` with …
=> Fix: sync store.pods[id].parent/position immediately on updates from anywhere

ui/src/lib/auth.tsx, ui/src/pages/repo.tsx
When refreshing on the repo page, the loadRepo call may be too early before user info is set (`useMe`). The new `hasToken` directly checks `localStorage`, thus can be an immediate indicator of whether the user has signed-in. Thus it is generally safer to use then `useMe`).
=> fix: add hasToken to avoid loading repo to early

api/src/resolver.ts, api/src/resolver_repo.ts, api/src/typedefs.ts, ui/package.json, ui/src/components/Canvas.tsx, ui/src/components/CanvasContextMenu.tsx, ui/src/components/Header.tsx, ui/src/components/ShareProjDialog.tsx, ui/src/lib/fetch.tsx, ui/src/lib/store.tsx, ui/src/pages/repo.tsx, ui/src/pages/repos.tsx, ui/yarn.lock
Change:
1. Remove the share-buttons on the dashboard, add it on the repo page.
2. Polish the share-project dialog, everyone accessing the repo can click the share-button (and the share option in right-click menu) to see the dialog, but the privilege levels vary: 
- A read-only URL field to copy 
- An owner can switch the visibility (public or private) by a button (ref:https://github.com/codepod-io/codepod/pull/142#issuecomment-1348105998)
- Explanation about the visibility when clicking the help icon
- Fetch a list of current collaborators, the owner can **delete any of them** by clicking the button
- Invite others by collaborators (if you are not the owner, it doesn't work)
- Change of the visibility  (`isPublic` and the list of collaborators) loads immediately after actions.
By the way, …
=> Feat: add a top-right share-button on the repo page

runtime/src/kernel.ts
The runtime no longer uses the languages' module systems.
Leave additional cleanup to the future.
=> remove deprecated kernel startup code

ui/src/components/Canvas.tsx, ui/src/components/MyMonaco.tsx, ui/src/lib/nodes.tsx, ui/src/lib/store.tsx
[Done] This PR is finished, ready to review now.
(Only support one single code pod by now, `Ctrl-C` is not supported yet)
Related to: https://github.com/codepod-io/codepod/issues/155
I gave up `clipboard.read/write`, removed the paste option in right-click menu, tested on Chrome, Edges, and Firefox, all works well.
How to use:
1. Copy a pod (either in this page or other pages) via the copy button
2. Click (or right-click) on the canvas (pane) once to make sure the pane is focused
3. Press `Ctrl` -`V`, a duplicated pod shows up in the center of the canvas (FIXME: because the cursor may not be in the canvas when pasting, so I just choose the center as the initial position, we can discuss the detailed rule for the initial position later)
4. Move your mouse inside the canvas, the …
=> Feat: cross-page single-pod copy-paste in mouse-bound `ctrl`-`v` way

ui/src/components/Canvas.tsx, ui/src/lib/nodes.tsx, ui/src/lib/store.tsx
~~Don't merge now, this is just a demo to align the idea of cut-n-paste functionality and tests. The code is too dirty now, clean-up is required after we agree on the idea.~~
Update: clean-up & ready for review.
How to use:
1. Click on the cut button of a pod, then the pod become half-transparent immediately.
2. This half-transparent pod will follow your mouse like pasting behavior.
3. Choose a destination location, click on it, the new pasted pod is located here and become solid.
4. If you don't want to proceed anymore, press <kbd>Esc</kbd>, the half-transparent pod disappears and the origin pod shows up again.
Note:
1. Like copying, the data will be written in your clipboard, you can still paste it into any repos even if your cutting procedure ends, until you copy new contents.
2. …
=> Feat: single-pod cut-n-paste support

ui/src/components/RichNode.tsx, ui/src/pages/repo.tsx
1. unselect all nodes when a RichNode is focused
2. remove run&change layout button for RichNodes
3. disable editing repo name for non-owner users
close https://github.com/codepod-io/codepod/issues/166
=> Fix: unselect all nodes when richnode is focused & disable repo name editing by non-owner users

ui/src/components/Canvas.tsx
The Result Block now gets updates during a stream of stdout. E.g., the following code will print stdout every second; previously, all numbers are printed at once in the end.
Also, call `React.memo` to avoid unnecessary re-renders on e.g. pod moves.
=> re-render ResultBlock on stream; memo it

ui/src/lib/store/repoMetaSlice.tsx, ui/src/pages/repo.tsx
1. now sync repo name every second instead of every keystroke
2. the repo name on the repo list page will be up-to-date
3. UI changes: show an "edit" tooltip on hover, and show editable textfield when focused.
Screenshot:
=> fix repo name sync time and UI

README.md, api/README.md, k8s/helm-chart/README.md, runtime/README.md
> Only the `README.md` files were changed in this Pull & Request
- Proper syntax highlighting for the code examples <small>(after those triple backticks)</small>
- Clickable links instead of bare links <small>(non-clickable for some Markdown parsers)</small>
- Native-like wording
=> docs: Wording changes and proper syntax highlighting

ui/src/components/Sidebar.tsx, ui/src/lib/store/repoStateSlice.tsx, ui/src/lib/store/runtimeSlice.tsx, ui/src/pages/repo.tsx
Properly set `connecting` and `connected`, and retry (every second) if not `connected` and not `connecting` (so that there won't be duplicated connection retries.
=> fix: stable retry connect for runtime and yjs sockets

ui/src/components/Sidebar.tsx, ui/src/lib/store/runtimeSlice.tsx, ui/src/pages/repo.tsx
Now the runtime connection feedback will be more smooth (no blinking). There's a restart button in the sidebar to restart the kernel.
=> smooth runtime connection with restart button

ui/src/components/MyMonaco.tsx, ui/src/components/Sidebar.tsx
Now when you toggle the "Scoped Variable" and "Enable Annotation" switches in sidebar, the editor annotations will change in real-time.
Also added tooltips.
=> fix: scoped func/var annotation re-rendering on switch

ui/src/components/Canvas.tsx, ui/src/components/CanvasContextMenu.tsx, ui/src/components/MyMonaco.tsx, ui/src/components/ShareProjDialog.tsx, ui/src/components/Sidebar.tsx, ui/src/components/nodes/Code.tsx, ui/src/components/nodes/Rich.tsx, ui/src/components/nodes/Scope.tsx, ui/src/lib/nodes.tsx, ui/src/lib/store/index.tsx, ui/src/lib/store/repoStateSlice.tsx, ui/src/lib/utils.tsx, ui/src/pages/repo.tsx
1. disable `richNode` editing & `codeNode` copying for guest users
2. fix the bug: a guest user sees the pasted pod increases on its size endlessly. 
3. fix the bug: a pasted pod's position is not up-to-date when adding.
4. extend node types when observing adding nodes in `nodesMap`
5. refactor the code about the privilege management in front-end, hide the detailed role info to simplify the code
More details can be found in comments.
Suggestions:
- Many functions in `canvas.tsx` can be moved into `lib/utils.tsx` like `dbtype2nodetype` to make `canvas.tsx` more clear.
- For a guest user, the runtime should not be loaded from the beginning, it wastes resource.
Other works on the way:
- Figure out a way to prevent selecting node by `Space` or `Enter` (see …
=> Fix: some miscellaneous & tiny bugs 

ui/src/components/Sidebar.tsx, ui/src/components/nodes/Code.tsx, ui/src/lib/store/settingSlice.tsx
Add a new "dev mode" switch in the sidebar. When it is on, the ID of all code pods will be displayed.
=> add devMode

ui/src/components/Sidebar.tsx, ui/src/lib/store/index.tsx, ui/src/lib/store/repoStateSlice.tsx
In the past, when we mark a pod `dirty`, it will sync (every second) with the remote server; once finished, clear the `dirty` flag. E.g.,
```dot
[update1] -> dirty=true -> sync1 -> sync1-return -> dirty=false
```
However, if a user updates the pod again before the sync finishes, this new update's `dirty` flag might be cleared by the sync request. E.g.,
```dot
[update1] -> dirty=true -> sync1 -> [update2] -> dirty=true -> sync1-return -> dirty=false
```
Also, there might be multiple sync requests for the same pod if the network lag is more than 1 second.
This PR adds a `pod.isSyncing` flag. The `dirty` flag is cleared immediately for the sync. The `isSyncing` flag is cleared once the sync request finishes.
=> fix potential pod syncing with pod.isSyncing

api/src/spawner-docker.ts, ui/src/lib/store/runtimeSlice.tsx
When the runtime is first spawned and not ready, the WebSocket connection will be **pending** for >2 min.
This PR adds a retry logic with a timeout. The retry will happen at 1s, 2s, 4s, 8s, 10s (max), 10s, ... This should fix the hopefully last runtime connection issue.
=> add runtime WebSocket retry logic

ui/src/components/Canvas.tsx, ui/src/components/MyMonaco.tsx, ui/src/components/nodes/Rich.tsx
1. Unselect all pods when a codeNode or richNode is focused.
2. Enlarge the difference when comparing the position value. `Number.EPSILON` is too small.
=> Fix: Minor fixes

ui/src/App.css, ui/src/components/Canvas.tsx, ui/src/components/MyMonaco.tsx, ui/src/components/nodes/Code.tsx, ui/src/components/nodes/Rich.tsx, ui/src/lib/store/canvasSlice.tsx
Fix:
1. Use the original border and change its style as red & dashed when the pod is under cutting
2. Fix the issue that resizing a codeNode/richNode will never trigger the store and DB sync.
=> Fix: incomplete dashed cutting hint

README.md, api/package.json, api/src/resolver.ts, api/src/resolver_export.ts, api/src/typedefs.ts, api/yarn.lock, compose/dev/compose.yml, ui/src/components/Sidebar.tsx
UI in the sidebar:
When clicked, the files will be downloaded. The exported python file with indentation:
The exported JSON file:
=> add python and JSON file export

ui/package.json, ui/src/App.css, ui/src/components/Canvas.tsx, ui/src/components/nodes/Code.tsx, ui/src/components/nodes/CustomConnectionLine.tsx, ui/src/components/nodes/FloatingEdge.tsx, ui/src/components/nodes/utils.tsx, ui/yarn.lock
1. Make the arrow handle stand out. Previously the right and bottom handles were covered by the Monaco editor and were hard to select.
2. Use undirectional floating edge. Previously the arrows are anchored at the 4 handles, which are not meaningful as we just need to know which nodes are the source/target. That also creates intermingled arrow connections. Now, the anchor of the arrow will move with the pods. Ref: https://reactflow.dev/docs/examples/nodes/easy-connect/
3. auto-hide the toolbar when the mouse is not over the pods.
Before:
After:
=> Refine Arrow connection UI

api/prisma/migrations/20230227022751_refine_edge/migration.sql, api/prisma/schema.prisma, api/src/resolver_repo.ts, api/src/typedefs.ts, ui/src/components/Canvas.tsx, ui/src/components/nodes/FloatingEdge.tsx, ui/src/lib/fetch.tsx, ui/src/lib/nodes.tsx, ui/src/lib/store/canvasSlice.tsx, ui/src/lib/store/repoStateSlice.tsx
close #210 
Now arrows will be saved to the remote database and reloaded on refresh.
Also, the arrow can now be selected, and its color will turn **red**. Pressing the `delete` key will delete the arrow.
TODO:
=> persist arrows to db

ui/src/lib/store/runtimeSlice.tsx
The import dependency of programs is not a tree, but a DAG (Directed Acyclic Graph). For example, an utility function may be used by many scopes. A tree structure cannot handle this, as there's only one parent for a tree node.
Now we can add an arrow from one scope to another to mark a manual import relation.
=> feat: add arrow-import runtime semantic

ui/src/components/nodes/FloatingEdge.tsx, ui/src/components/nodes/utils.tsx
close #223 
Now the arrows are anchored at the four handles and will move according to the relative positions of the connected nodes.
From:
To:
=> use BezierPath for arrows; anchor at four handles

api/src/resolver_repo.ts, api/src/typedefs.ts, ui/src/components/nodes/Code.tsx, ui/src/lib/fetch.tsx, ui/src/lib/store/podSlice.tsx
Previously, when a pod is deleted:
1. the `deletePods` GraphQL API call is fired.
2. the `deleteEdge` GraphQL API call is fired for all connected edges.
However, the `deletePods` operation might be executed before the edges are deleted, causing errors.
Now, this PR makes `deletePods` delete connected edges as well before the actual deleting of pods.
=> properly delete connected edges when deleting pods

ui/src/components/nodes/Code.tsx
The regression was introduced in #221 when `FloatingToolbar` is extracted as a stand-alone function. The `layout` is used in the `Code` component but `setLayout` is called inside the toolbar.
=> fix ResultBlock's setLayout button regression bug

ui/src/components/Canvas.tsx, ui/src/components/nodes/Scope.tsx, ui/src/lib/store/canvasSlice.tsx
1. Limit the draggable area of a scope to only the title bar (the same position as code nodes)
2. Right-click Menu in a scope node, you can create new nodes right in this scope instead of creating them outside and then dragging them into
Note: To make sure the created node totally inside the scope, it will adjust the position of the new created node like how you drag an existing node into a scope. However, the adjustment is pretty limited because we still lack an auto-layout logic of all nodes. Something funny may happen if you create a scope in a newly-created scope because they have the exact size (default size), you can hardly separate them then. **Refactoring is required after auto-layout/resize is implemented**.
=> Fix (better drag-n-drop): Scope Handler & Scope right-click Menu for adding new nodes

ui/src/components/nodes/Code.tsx
The "floating toolbar" appears when the mouse enters the pod. To hide the toolbar, previously, we set `display: none`. This seems to trigger a warning of MUI's Tooltip component. This PR sets `opacity: 0` to hide the toolbar instead.
=> fix floating toolbar anchorEl warning

ui/src/App.css, ui/src/components/Canvas.tsx
"Highlighting a scope" currently means adding a box-shadow. A scope is highlighted when:
1. it is "selected" by clicking on its header bar
2. the user move a pod over it, indicating the recipient scope
Specifically, this PR:
1. remove the hovering highlight because it's confusing and too eye-catching
2. fix the logic of removing the highlighting at the dragging end.
=> proper scope highlighting

ui/package.json, ui/src/components/Canvas.tsx, ui/src/components/MyKBar.tsx, ui/src/components/Sidebar.tsx, ui/src/lib/store/canvasSlice.tsx, ui/yarn.lock
Now auto-shrink or enlarge the scopes to fit its children. This PR also adds a Command Palette triggered by Ctrl+k (or Cmd+k on macOS) via [kbar](https://github.com/timc1/kbar); auto-layout can be invoked in the Command Palette. In the future, we could add a setting option to run auto layout automatically. Screenshot:
Before auto-layout, and the Command Palette:
After auto-layout:
=> feat: add auto shrink

api/src/resolver_repo.ts
Fix a bug when deleting a repo, introduced by adding the userRepoData in #219.
=> fix: delete user repo data before deleting a repo

ui/src/components/nodes/Scope.tsx, ui/src/lib/store/canvasSlice.tsx, ui/src/lib/store/runtimeSlice.tsx
Now there's a `Run` button for the scope. It will run all pods and scopes inside by geographical (top-down, left-right) order. Screenshot:
=> feat: geographical order based scope execution

ui/src/components/Canvas.tsx, ui/src/lib/fetch.tsx, ui/src/lib/nodes.tsx, ui/src/lib/store/canvasSlice.tsx, ui/src/lib/store/index.tsx, ui/src/lib/store/runtimeSlice.tsx, ui/src/lib/utils.tsx
Now all front end code uses the consistent node types `CODE, SCOPE, RICH`. The backend still uses `CODE, DECK, WYSIWYG` because it isn't straightforward to migrate the DB. Importantly, now the conversion happens only in `fetch.tsx`
=> refactor: node type CODE, SCOPE, RICH in front-end

ui/src/components/nodes/Code.tsx, ui/src/components/nodes/Scope.tsx
Now the edge handles will only appear when you move over a pod or a scope.
=> feat: auto hide edge handles

ui/src/components/Canvas.tsx, ui/src/components/Sidebar.tsx, ui/src/lib/store/canvasSlice.tsx, ui/src/lib/store/settingSlice.tsx
Add a new setting, "auto-run layout". If it is switched on, the d3-force layout algorithm will run automatically when:
* at the end of node dragging
* adding a new node
The setting:
Before adding a node:
After:
=> feat: add auto-run setting for auto-layout

ui/src/App.css, ui/src/components/nodes/Code.tsx, ui/src/components/nodes/Rich.tsx, ui/src/components/nodes/Scope.tsx
Now the pods and scopes can only be dragged by the drag handle in the floating toolbar:
The headers of code and rich-text pods are removed. The scrollbar of Remirror is removed. The UI should be very clean now.
=> feat: add drag handles; remove Remirror's scrollbar

api/src/resolver_repo.ts
The bug prevented deleting a repo that has been shared with others. The fix is to delete all UserRepoData associated with it.
=> fix: cannot delete repos shared with others

api/prisma/migrations/20230501222052_add_isguset_field/migration.sql, api/prisma/schema.prisma, api/src/resolver_user.ts
The guest user's ID was `guset_<nanoid>`. This creates potential consistency issues when handling the userId.
Now we remove the `guest_` prefix and add a `isGuest` field to the DB table instead.
=> add isGuest field and make guest userId the same format as registered users

ui/src/lib/store/settingSlice.tsx
The auto-layout algorithm now detects only circle collision, which is not ideal.
The auto-run was enabled by default in #246 . Now disable this by default in setting.
=> set autorun-layout setting default to false

ui/src/App.css, ui/src/components/Canvas.tsx
Dragging on the toolbar handle into the scope might not work.
This is because the new darg handler in the toolbar (#248) is outside of the node, and there was a check that will prevent moving into a scope. The check was used to restrict a node not to be moved outside its parent scope. This restriction was removed in #236 to support auto-shrink/enlarge, so we no longer need to check the positions. Removing that check fix the regression.
The scope should have a shadow when a node is dragging over it. The dragging shadow was not working due to a CSS class name change in #241, this PR fixes that as well.
=> fix: drag on toolbar handle into a scope

ui/src/components/nodes/Code.tsx, ui/src/components/nodes/Rich.tsx, ui/src/components/nodes/Scope.tsx
The cursor will only be shown as "grab" when it is over the handle, so that it is more clear to users as to where to drag.
=> show `cursor: grab` only on drag handle

ui/src/components/nodes/Rich.tsx
Now you can drag and drop a picture onto the rich-text editor. It supports resizing the image.
=> use remirror image extension

ui/src/components/nodes/Rich.tsx, ui/src/components/nodes/YjsRemirror.tsx, ui/yarn.lock
Now the rich-text editor supports Yjs real-time sync. Use the same y-websocket adapter.
=> feat: add remirror yjs extension for rich-text real-time sync

ui/src/App.css, ui/src/components/nodes/Rich.tsx
To insert a table into the rich-text editor, type `/table` then press `<enter>`. Note:
1. must type in full `/table`; selecting from the drop-down table won't work.
2. the `/table` text will be inserted. Ideally we'd remove it after a table is inserted.
These are the limitations of using the `MentionExtension` to implement slash commands.
=> feat: add slash command to insert remirror table

ui/yarn.lock
#260 updated `yarn.lock` and upgraded web-tree-sitter package from `0.20.7` to `0.20.8`, which broke the loading of tree-sitter wasm with the following error. This is weird; this PR revert the version.
```
Uncaught (in promise) RuntimeError: Aborted(LinkError: WebAssembly.instantiate(): 
Import #1 module="env" function="setTempRet0" error: function import requires a callable). 
Build with -sASSERTIONS for more info.
at abort (tree-sitter.js:1:6824)
at tree-sitter.js:1:8574
```
=> fix: web-tree-sitter load wasm error

ui/src/lib/fetch.tsx, ui/src/lib/store/podSlice.tsx
The results are now saved to DB, which will be reloaded after refreshing or re-opening the project.
=> feat: persist execution results to DB

ui/src/lib/parser.tsx
The `node` parameter might be undefined. Add a safety check for all the compileXXX functions.
=> fix: check undefined nodes in compileXXX functions

ui/src/components/Canvas.tsx, ui/src/components/HelperLines.tsx, ui/src/components/nodes/utils.tsx, ui/src/lib/store/canvasSlice.tsx
When dragging a node, it will snap to align with other pods. Helper lines will appear to guide the dragging.
If the moving pod is inside a scope, the pod will only snap to other pods inside the same scope.
Reference: https://reactflow.dev/docs/examples/interaction/helper-lines/
=> feat: add snapping with helper lines

ui/src/lib/parser.tsx
Introduced in #268, where the `node.children` is replaced with `node.namedChildren` but forgets to update the receiving variable list.
```diff
@@ -694,11 +694,11 @@ function compileExpression(node: Parser.SyntaxNode, st) {
case "await":
return compileExpression(node.firstNamedChild!, st);
...
case "binary_operator":
case "boolean_operator": {
-      let [left, , right] = node.namedChildren.filter(notComment);
+      let [left, , right] = node.children;
compileExpression(left, st);
compileExpression(right, st);
```
Now, both a() and b() can be recognized.
=> fix: binary-op parsing

ui/src/lib/store/canvasSlice.tsx
The d3-force-layout applies the physical force to the nodes in iterations. We used 1 iteration, but it may not fully push nodes apart. Now we use 10.
Before:
After:
=> add more auto-layout ticks

ui/src/App.css
We have to set `.react-flow__edges`'s `z-index` property. Reference: https://github.com/wbkd/react-flow/issues/3020#issuecomment-1527349777.
You can select an edge by clicking on it, which will turn red. Press `<backspace>` to delete the edge.
Before:
After:
=> fix edge zindex to make edges selectible above scope background

ui/src/components/Canvas.tsx, ui/src/lib/store/canvasSlice.tsx
Now when moving a pod, it can be moved into any scope, including ROOT scope.
At this point, the drag-n-drop behavior is very straightforward: just drag it anywhere and it will be moved there. The cut-n-paste function is now deprecated.
=> allow pod to be moved into ROOT scope

api/src/resolver_repo.ts, ui/src/components/Canvas.tsx
Fixed two bugs related to #280:
1. when updating the parent node to ROOT in DB, we need to disconnect the previous parent pod, because Prisma treats `undefined` as `do nothing` instead of `disconnect`.
2. correctly compare the ROOT scopeID to avoid duplicate moveIntoScope calls
=> fix: disconnect parentnode in DB; fix ROOT scopeId compare

ui/src/App.css, ui/src/components/Canvas.tsx, ui/src/components/MyMonaco.tsx, ui/src/components/Sidebar.tsx, ui/src/components/nodes/Code.tsx, ui/src/components/nodes/Rich.tsx, ui/src/components/nodes/Scope.tsx, ui/src/components/nodes/remirror-size.css, ui/src/lib/store/canvasSlice.tsx, ui/src/lib/store/settingSlice.tsx
This PR introduces a major feature called "contextual zoom". The idea is to see different level of details at different zoom levels, so that users can focus on a small subsets of content to work on. Think of it as Google maps where you zoom in & out to see different levels of details.
The feature contains roughly two significant behaviors:
1. different levels in the hierarchy have **different font sizes**
2. when zooming out, the pods and scopes that become too small to view will be **collapsed into a block, with large text summarizing its content**. These blocks can be dragged and moved easily (which is pretty easy to use).
This feature is experimental and disabled by default. There's a setting `contextual zoom` in the sidebar to enable it.
Future work
=> feat: add contextual zoom

ui/package.json, ui/src/components/Sidebar.tsx, ui/yarn.lock
There's a "download image" button in the sidebar. Once clicked, a high-quality SVG file will be generated (for the **current viewport** of the canvas). The file name is `<reponame>-<repoId>-<ISOdate>.svg` so that it is easy to backup your work with version info.
The SVG file can be big, e.g., 5MB. You can then convert it into pdf, which makes it 150KB.
The UI screenshot:
Generated .svg file:
=> feat: add export to svg

ui/src/components/Canvas.tsx, ui/src/components/MyKBar.tsx, ui/src/components/nodes/Scope.tsx, ui/src/lib/nodes.tsx, ui/src/lib/store/canvasSlice.tsx, ui/src/lib/store/runtimeSlice.tsx
Now a pod can access all names defined in its ancestor scopes. The following canvas shows 4 examples:
1. **[new behavior]** function can be accessed in an inner scope
2. **[new behavior]** global variables can be accessed anywhere
3. exported name can be accessed in its parent scope
4. unexported name cannot be accessed in its parent scope
Technical staff: this PR also supports ROOT in Node2Children map, and auto-build it.
=> feat: allow pod to access to names in all ancestor scopes

ui/src/components/nodes/Code.tsx, ui/src/components/nodes/Rich.tsx
The auto-layout algorithm will now be triggered:
1. when you resize a pod
2. when you delete a pod (the code was accidentally committed in https://github.com/codepod-io/codepod/pull/284#discussion_r1186763795)
=> run auto-layout on pod resize

ui/src/components/MyMonaco.tsx, ui/src/lib/parser.tsx, ui/src/lib/store/canvasSlice.tsx, ui/src/lib/store/index.tsx, ui/src/lib/store/runtimeSlice.tsx
An exported function or variable can now be further exported to ancestor scopes. To use this, create a new pod in the parent scope with:
```
@export foo
@export x
```
Note that `@export` must be the **first character** of the line.
Before, no recursive export, the outer scope cannot see the definitions:
After, with the recursive @export bridging pod:
=> feat: add recursive @export

ui/src/lib/store/podSlice.tsx, ui/src/lib/store/runtimeSlice.tsx
Fix a bug that set the pod as running before checking the socket connection. This caused pod execution to be blocked.
=> fix: do not set pod as running when socket isn't connected

ui/src/components/nodes/Code.tsx, ui/src/lib/store/index.tsx, ui/src/lib/store/podSlice.tsx, ui/src/lib/utils.tsx, ui/src/pages/repos.tsx
close #277
Now the green tick will only show upon a successful run in the current session; e.g., refreshing the page will remove all ticks.
Also show last executed time.
=> show green tick for runs in the current session; show last executed at

ui/src/components/nodes/Code.tsx, ui/src/components/nodes/Rich.tsx, ui/src/components/nodes/Scope.tsx
The previous drag handle was on the top right corner. It is difficult to drag to the right without moving out of the parent scope.
In our early discussion, we would like to put the toolbar in all four corners. But this is not easy or clean to implement (e.g., needs to attach four elements to bind the onMouseEnter/Leave callbacks).
This PR is good enough for me to move a pod around.
Screenshot:
=> add a left drag handle on the toolbar (deprecate the 4 handle idea)

api/src/server.ts
Fix the "Payload Too Large" error when saving output images and rich-text images. Reference: https://github.com/apollographql/apollo-server/issues/288
=> allow up to 20MB graphql payload

ui/src/components/nodes/Code.tsx, ui/src/components/nodes/Rich.tsx
The pod size might jump back after resizing. The bug was introduced in #285 , the reason is we set `nodeMap.set({width:}`, but missed `nodeMap.set({width, style: {width})`
=> fix: unexpected jumpback after resizing

ui/src/components/nodes/Code.tsx
More specifically, on results **status** change (**start or end**), i.e., whenever the following circular progress indicator **show** or **disappear**. It won't run when the output is still expanding.
=> run auto layout on result change

ui/src/lib/store/canvasSlice.tsx
Before, the pod toolbar can overlap with (1) scope header or (2) another pod:
After, leave more rooms:
=> auto-layout leave some room for toolbar

ui/src/components/nodes/Code.tsx
A new focus button is added to the result area.
- Once **focused**, the border will become red-colored, and you can **scroll inside the result area**. Click "unfocus" button to un-focus it.
- If **not focused**, you can **pan (move) the canvas** when your cursor is over the result area.
=> add result focus button and mode

ui/src/lib/parser.tsx
Fix a regression introduced in #286 that causes all `vardef`s to be un-resolved. Now directly parse module-level variable definitions.
=> fix: vardef parsing

ui/src/lib/store/runtimeSlice.tsx
If the pod is empty, the kernel won't reply, and this will block all future runs. So, we need to skip it.
=> fix: skip running an empty cell

ui/src/lib/parser.tsx, ui/src/tests/parser.test.tsx
When LHS is a subscript or an attribute, we should parse it as `varuse`, not `vardef`. The following two examples should now work:
close #309
=> fix: compileLHS for subscript and attribute

ui/src/components/nodes/Code.tsx, ui/src/components/nodes/Rich.tsx, ui/src/lib/store/canvasSlice.tsx
On repo's initial loading or refreshing, there were "dirty" pods that gets uploaded.
There are three causes, all fixed:
1. the auto-layout engine was run upon Code cell's `running` and `layout` states in `useEffect`, even if they are not changed. Now it is only triggered when the state is changed.
2. There were dimension change events from reactflow's `onNodeChange` without actual change. Now this is filtered out.
3. Rich text editor will fire a "change" event at the beginning. This is also filtered out.
=> fix: dirty status on repo initial loading

ui/src/components/Canvas.tsx, ui/src/lib/store/canvasSlice.tsx
You can now use arrow keys to jump between pods. Steps:
1. select a pod by clicking on the drag handler.
2. press arrow keys (up, down, left, right)
The jumping honers the scope, i.e., you will only jump to pods within the same scope.
https://github.com/codepod-io/codepod/assets/4576201/ae0b8e17-d7b6-44ee-9dd2-686618e711b8
=> feat: add jump between pods

ui/src/components/nodes/Code.tsx
Changed the layout of the output menu options to vertical and put them on top of the output box. The menu options will only appear when the user's mouse hovers on the output box.
=> Updated layout and added auto hide for output menu options

ui/src/components/nodes/Code.tsx
Adjust how output box options are displayed: 
Ref: https://github.com/codepod-io/codepod/issues/321
=> stylize output box options

ui/src/components/CanvasContextMenu.tsx, ui/src/components/Sidebar.tsx, ui/src/lib/store/settingSlice.tsx
- Add the toggle switch in sidebar
- remove the menu item from Right Click menu.
-
=> Apply "Show Line Numbers" as toggle switch in sidebar

README.md
All documents will be maintained in the website repo ([codepod-io/codepod.io](https://github.com/codepod-io/codepod.io)) so that people can browser the documents easily on our website.
Related PR: https://github.com/codepod-io/codepod.io/pull/9
The developer manual is at https://codepod.io/docs/developer
=> move dev manual to codepod.io reop

ui/src/components/Sidebar.tsx, ui/src/lib/store/index.tsx, ui/src/lib/store/repoStateSlice.tsx
One `dirty` status isn't enough. If a new change happens after a previous remote API sync but before the API response, the new dirty status will be cleared, causing the new change not written to remote.
This PR fixes it, by adding a temporary dirty status used specific during/for remote API syncing.
=> fix content loss caused by `dirty` status override

ui/src/components/Canvas.tsx, ui/src/components/nodes/Rich.tsx, ui/src/lib/store/canvasSlice.tsx
New behaviors:
1. the remirror floating toolbar will follow the Rich-text pod when panning on canvas.
2. it will disappear when you click on the canvas
(minor) Also fixed an issue that prevented canvas-panning when mouse is over the remirror toolbar.
https://github.com/codepod-io/codepod/assets/4576201/5822151d-4f6e-4ffb-91a5-b0298cfa7af7
=> fix remirror toolbar position when panning on canvas

compose/dev/compose.yml, compose/dev/nginx.conf
Use `:8080` instead of `:80` for development.
* `:80` port isn't intuitive for development, and
* many systems need sudo privilege to open `:80` port.
=> use :8080 port by default

ui/src/components/Canvas.tsx
`console.log("No node selected")` was printed too often. Filter the key-strokes at the beginning of useJump.
=> chore: filter keys in the beginning of useJump

ui/src/components/Sidebar.tsx
Fix two errors in the browser developer console:
=> fix: two console errors from #328

api/src/client.ts, api/src/resolver_export.ts, api/src/resolver_repo.ts, api/src/resolver_runtime.ts, api/src/resolver_user.ts
This PR follows [Prisma's official best practice](https://www.prisma.io/docs/guides/performance-and-optimization/connection-management#prismaclient-in-long-running-applications). Hopefully this would reduce the number of active connections and fix the following error:
```
Error querying the database: db error:
FATAL: remaining connection slots are reserved for non-replication superuser connections
```
=> use one global instance of Prisma client

ui/src/pages/repos.tsx
before:
- no loading state for deleting a repo
- no instant feedback after a repo deleted
after:
caveat:
Directly remove deleted repo from Apollo Client cache after mutation succeeded instead of refetching repo list to provide that instant UI feedback. 
https://www.apollographql.com/docs/react/data/mutations/#updating-local-data
=> chore: enhance delete repo UX

ui/src/pages/repos.tsx
Fix the following warning in dashboard page, introduced in #364 :
=> fix: sx not an object warning

ui/src/components/Canvas.tsx, ui/src/components/CanvasContextMenu.tsx, ui/src/lib/store/canvasSlice.tsx
- Allow importing a Python script to a pod.
- Change right-click context menu item
- The imported Python script is put into a scope rather than "ROOT".
=> [UI] Allow importing the Python script

ui/src/components/MyMonaco.tsx, ui/src/lib/store/repoStateSlice.tsx
Adopting a [better workaround](https://github.com/microsoft/monaco-editor/issues/2947#issuecomment-1639608153) (replacing the fix in #70) to handle Monaco's multiple instances bug.
=> use Monaco's addAction instead of addCommand

api/src/spawner-docker.ts, compose/dev/compose.yml
Now the `runtime/src` folder is mounted into the spawned docker runtime. As a result, now it is possible to debug the runtime source code. I.e., changing the source code of the `runtime/` folder will be immediately visible.
=> mount runtime src into spawned docker container for development

ui/src/components/nodes/Rich.tsx
This is easier and more intuitive for users to open the link.
=> add a toolbar with edit & open buttons when user clicks on a link

ui/src/components/nodes/Code.tsx, ui/src/components/nodes/Rich.tsx
The height of a collapsed Code or Rich node is changing due to the border size of 5px. This PR offsets that wth a -5px margin.
=> fix: node height changing bug caused by border

ui/src/components/nodes/utils.tsx
The previous "new pod" buttons on the side are prone to accidental clicks.
From
To
=> make newpod buttons non-overlap with editor

ui/src/components/nodes/Rich.tsx
The link toolbar is now more responsive. Just click the link once. Previously needed twice due to lagged React re-rendering.
=> fix link toolbar lag

ui/src/components/nodes/Rich.tsx
Now you can type `[text](https://google.com)` to create a link. Close #172
=> add markdown link input rules for Rich editor

ui/src/components/nodes/Rich.tsx, ui/src/components/nodes/extensions/list.ts
Two changes:
1. there is a spine (left ruler) to visually align the lists
2. A nested ordered list will show markers with different styles at different levels.
From:
To:
=> add spine to lists; add list-style for nested <ol>

ui/src/components/nodes/Rich.tsx, ui/src/components/nodes/extensions/link.tsx
Put relative code into a separate file `extensions/link.tsx`
=> refactor: Remirror link extension

ui/src/components/nodes/Rich.tsx
Fix the following error, introduced in #392 :
=> fix: kebab-case sx property error

api/src/spawner-docker.ts, compose/dev/compose.yml
How runtime container is spawned in docker:
1. By default, use the pre-built runtime docker image.
2. If you want to develop the source code of `runtime/` module, set `PROJECT_ROOT` to your local codepod repo's absolute path.
Fix a hard-coded path problem that prevent runtime containers from starting.
=> fix: docker spawner runtime container mount math

ui/src/components/nodes/Code.tsx, ui/src/components/nodes/Rich.tsx, ui/src/components/nodes/Scope.tsx, ui/src/components/nodes/extensions/codepodSync.ts, ui/src/lib/store/podSlice.tsx
The [controlled Remirror editor](https://remirror.io/docs/controlled-editor) will prevent Chinese (or CJK) input methods from working.
Remirror's official demo:
- **Un-controlled** Remirror editor, Chinese input working: https://remirror.vercel.app/?path=/story/editors-markdown--basic
- **Controlled** Remirror editor, Chinese input NOT working: https://remirror.vercel.app/?path=/story/editors-controlled--editable
This PR changes **Controlled** Remirror editor to **Un-controlled**.
=> fix: Chinese input method in Remirror editor

api/src/resolver_export.ts, runtime/src/zmq-utils.ts, ui/src/components/Canvas.tsx, ui/src/components/Sidebar.tsx, ui/src/lib/store/canvasSlice.tsx
- When exporting, the pod's stdout and result are written to a Jupyter notebook
- "Raw JSON" export functionality is moved to the frontend
- The Jupyter notebook result is imported in addition to the entire notebook
- Bug fix: "execution_count" is returned from runtime server now
=> [UI] Support exporting pod stdout and result

ui/src/App.css, ui/src/components/Canvas.tsx, ui/src/components/nodes/Rich.tsx, ui/src/components/nodes/extensions/blockHandle.ts
This PR implements a Notion-style block editor with drag handles as a Remirror plugin. Developed based on code in this comment: https://github.com/ueberdosis/tiptap/issues/323#issuecomment-506637799
https://github.com/codepod-io/codepod/assets/4576201/9ea8c9c1-2a7e-4300-9314-4905676ba95f
=> feat: add Notion-style block editor drag handle

ui/src/pages/repo.tsx
So that the longer titles will be shown gracefully.
Before:
After:
=> auto-change textfield size of repo title

ui/src/components/Sidebar.tsx, ui/src/lib/store/canvasSlice.tsx, ui/src/lib/store/index.tsx
- For Jupyter notebook export
- Better align the pod result with Jupyter cell output format, issue #411 
- Add error output
- separate `execute_result` and `display_data`
- For Jupyter notebook import 
- Support `error` imports
- Improve exported .ipynb readability
- Add repo_id into the top-level `metadata`
=> [UI] Jupyter notebook export patch

ui/src/components/nodes/Code.tsx, ui/src/components/nodes/Rich.tsx, ui/src/components/nodes/Scope.tsx, ui/src/components/nodes/utils.tsx, ui/src/pages/profile.tsx
The new-node buttons in #274 are too clumsy. This PR uses a pop-up menu instead. You can bring up the menus by clicking on the 4 edge handles.
=> feat: use popup handles to create new nodes

api/src/resolver_repo.ts, api/src/typedefs.ts, ui/src/pages/repos.tsx
* Unify `myRepos` and `myColabRepos` into one `getDashboardRepos`. This also fix a bug that the `myColabRepos` query wasn't re-fetched.
* Refactor dashboard components to have clean state variable passing.
* Use Cards instead of Tables in the dashboard. Tables are very hard to maintain, e.g., add a field
Before:
After:
=> refactor: dashboard

ui/src/pages/repos.tsx
=> [UI] make dashboard cleaner

api/src/yjs-server.ts, api/src/yjs-setupWS.ts, ui/src/lib/store/repoStateSlice.tsx
1. Front-end sends the user token with the Yjs WebSocket request.
2. Yjs-server validates that the user has read or write access before connecting the WebSocket. This PR also handles read/write access differently at Yjs level.
=> feat: add authentication to yjs server

ui/src/components/Canvas.tsx, ui/src/components/MyMonaco.tsx, ui/src/components/nodes/Code.tsx, ui/src/components/nodes/Rich.tsx, ui/src/components/nodes/Scope.tsx, ui/src/lib/store/canvasSlice.tsx
PR #398 introduced CMD mode, and issue #418 and #420 reveal some improvement and bugs.
- For #418,
- To go into a scope, the key combination is adjusted to `SHIFT` + `ArrowDown`
- To go to a parent scope, the key combination is adjusted to `SHIFT` + `ArrowUp`
- For #420, the reason is that `useJump()` uses `selectedPods` to choose the `from` node, while in a multi-selection scenario, `selectedPods` contains more than 1 node. As a workaround, a new state variable `cursorNode` is added for a single node selection.
- The toolbar pops-up while jumping to a node
- Misc
- On a code pod, pressing `SHIFT`+`Enter` will run the pod
- On a scope, pressing `SHIFT`+`Enter` will run the scope
=> [UI] Edit cmd mode patch

ui/src/components/nodes/utils.tsx, ui/src/pages/profile.tsx
Two fixes:
1. click-away (clicking on anywhere but the popper) will close the popper
2. move the canvas will also close the popper
fix #430
=> fix: click away listener for add-node handle popper

ui/src/components/nodes/Code.tsx, ui/src/components/nodes/Rich.tsx, ui/src/components/nodes/Scope.tsx
The toolbar icons will now increase in size to compensate when zooming out to help with visibility. Fixes #317. 
https://github.com/codepod-io/codepod/assets/105993789/4d4f570d-2d28-47c4-a560-f4b96f8a8c46
I also adjusted the toolbar placement for scopes slightly so it would not block the scope title when zoomed out.
=> Tool bar size adjustment when contextually zooming out

ui/src/components/nodes/utils.tsx
Make it pannable and zoomable when the pointer is over the popup menus (The handle popper in #421).
=> disable portal to allow paning over handle menus

runtime/src/kernel.ts, runtime/src/zmq-utils.ts, ui/src/components/Sidebar.tsx, ui/src/components/nodes/Code.tsx, ui/src/lib/store/canvasSlice.tsx, ui/src/lib/store/index.tsx, ui/src/lib/store/podSlice.tsx, ui/src/lib/store/runtimeSlice.tsx
Currently, the kernel messages are concatenated and stored in a single object, i.e., `pod.result`. This concatenation behavior creates a few discrepancy with Colab regarding the output results, e.g., it can't produce multiple plots in a single pod, the order of line execution might confuse users (see screenshots in Test section)
- <img width="512" alt="Screenshot 2023-08-04 at 10 41 48 PM" src="https://github.com/codepod-io/codepod/assets/10226241/280e9312-228b-4152-a6e5-b5f1ba9ce4f1">
- <img width="635" alt="Screenshot 2023-08-04 at 10 40 19 PM" src="https://github.com/codepod-io/codepod/assets/10226241/42c2c45e-d66e-420d-8da2-9b03684b5c23">
- Export/Import also verified
- The `ResultBlock` in `Code.tsx` needs more tuning
- We might need to support more message types, [Messaging in …
=> [Backend] Refactor ipynb kernel messages serialization

ui/src/components/Canvas.tsx, ui/src/components/MyMonaco.tsx, ui/src/components/nodes/Code.tsx, ui/src/components/nodes/Rich.tsx, ui/src/components/nodes/Scope.tsx
- Drag-n-drop the entire pod by dragging anywhere within the pod
- "Double click" to enter `Edit` mode.
- Bug: Monaco editor's cursor can't be hidden in `CMD` mode
=> [UI] Drag-n-drop entire pod/scope

api/src/yjs-blob.ts, api/src/yjs-plain.ts, ui/src/components/Canvas.tsx, ui/src/components/MyMonaco.tsx, ui/src/components/nodes/Code.tsx, ui/src/components/nodes/Rich.tsx, ui/src/components/nodes/Scope.tsx, ui/src/lib/nodes.tsx, ui/src/lib/store/canvasSlice.tsx, ui/src/lib/store/runtimeSlice.tsx
Instead of using four top-level YMaps (`nodesMap`, `edgesMap`, `codeMap`, `richMap`), this PR uses a root YMap `rootMap`, so that all fields are removable for possible future schema updates.
Before:
```ts
const nodesMap = ydoc.getMap<ReactflowNode<NodeData>>("nodesMap")
const edgesMap = ydoc.getMap<ReactflowEdge>("edgesMap")
const codeMap = ydoc.getMap<Y.Text>("codeMap")
const richMap = ydoc.getMap<Y.XmlFragment>("richMap")
```
After:
```ts
// rootMap
const rootMap = ydoc.getMap("rootMap");
// nested maps
const nodesMap = rootMap.get("nodesMap") as Y.Map<ReactflowNode<NodeData>>;
const edgesMap = rootMap.get("edgesMap") as Y.Map<ReactflowEdge>;
const codeMap = rootMap.get("codeMap") as Y.Map<Y.Text>;
const richMap = rootMap.get("richMap") as Y.Map<Y.XmlFragment>;
```
Also added four …
=> use root YMap

api/src/yjs-blob.ts
Fixed two bugs:
* forgot to await on the async function `migrate_v_0_0_1`
* a typo in `rootMap.set()`
=> fix: await bug; rootMap.set typo

api/src/yjs-setupWS.ts
Loading persisted `ydoc` takes time, and if `SyncStep1` is sent/received before `ydoc` is ready, the message is discarded, causing `provider.synced` event never being fired.
This PR adds messages to a queue and processes them after ydoc is loaded from persistence. Ref: https://github.com/yjs/y-websocket/issues/81#issuecomment-1453185788
=> fix: queue sync1 message and handle it after ydoc is loaded

ui/src/components/nodes/Code.tsx, ui/src/components/nodes/Rich.tsx
When a pod is selected, single-click on it to enter edit mode.
=> UI: single click to edit when pod is selected

ui/src/lib/store/canvasSlice.tsx
=> fix: compile error

ui/src/components/Canvas.tsx, ui/src/components/MyMonaco.tsx, ui/src/components/Sidebar.tsx, ui/src/components/nodes/Code.tsx, ui/src/components/nodes/Rich.tsx, ui/src/lib/nodes.tsx, ui/src/lib/store/canvasSlice.tsx, ui/src/lib/store/podSlice.tsx, ui/src/lib/store/repoStateSlice.tsx, ui/src/lib/store/runtimeSlice.tsx, ui/src/pages/repo.tsx
This is follow-up PR for #331 to fix broken things.
What's changed:
- state.pods are removed and fixed all compile errors
- Runtime and results are fixed.
Remaining TODOs regarding this centered-Yjs transition:
=> remove state.pods; fix runtime & results

ui/src/components/Canvas.tsx, ui/src/components/nodes/Code.tsx, ui/src/components/nodes/Scope.tsx, ui/src/components/nodes/extensions/link.tsx, ui/src/lib/store/canvasSlice.tsx, ui/src/lib/store/podSlice.tsx, ui/src/lib/store/repoStateSlice.tsx
New behavior: 
1. select a pod,
2. `ctrl-c` to copy, and
3. `ctrl-v` to paste at the **current mouse position** (the same behavior in [reactflow's example](https://reactflow.dev/docs/examples/interaction/copy-and-paste/)).
TODOs:
=> simplify copy-n-paste

ui/src/components/Canvas.tsx
Easier to drag select pods by dragging partially over them. Recall that drag select is holding shift, then drag a region.
=> set partial selection mode

ui/src/lib/store/canvasSlice.tsx
Following up PR #452, now edges are copied as well.
=> feat: support copying edge

ui/src/components/Sidebar.tsx
When creating a new project, the `ToC` is failed to render due to empty `node2children`
=> [UI] Fix ToC failure due to empty node2children

ui/src/components/Canvas.tsx, ui/src/components/MyMonaco.tsx, ui/src/components/Sidebar.tsx, ui/src/components/nodes/Code.tsx, ui/src/components/nodes/Rich.tsx, ui/src/components/nodes/Scope.tsx, ui/src/lib/store/canvasSlice.ts
Two changes:
- #458 introduced a changing behavior: selecting a pod will trigger a centering event. This PR removes that behavior. Centering event is triggered by `state.setCenterSelection(true)`
- `state.CursorNode` (introduced in #431) has been confusing with `state.SelectedPods`. We mentioned that we want to unify the two in https://github.com/codepod-io/codepod/pull/431#issuecomment-1665767266. Therefore, this PR removes `CursorNode` to use only `SelectedPods`.
=> remove CursorNode, fix pod center-on-selection

ui/src/components/nodes/Code.tsx, ui/src/lib/store/podSlice.ts, ui/src/lib/store/runtimeSlice.ts
A minor refactor to remove deprecated `stdout`/`stderr`, as they are handled and saved in `stream` type.
=> refactor: remove stdout/stderr in results

api/src/resolver.ts, api/src/resolver_yjs.ts, api/src/typedefs.ts, api/src/yjs-blob.ts, api/src/yjs-runtime.ts, api/src/yjs-server.ts, api/src/yjs-setupWS.ts, compose/dev/compose.yml, proxy/src/node-proxy.ts, ui/src/components/Canvas.tsx, ui/src/components/MyMonaco.tsx, ui/src/components/Sidebar.tsx, ui/src/components/nodes/Code.tsx, ui/src/components/nodes/Scope.tsx, ui/src/lib/store/canvasSlice.ts, ui/src/lib/store/podSlice.ts, ui/src/lib/store/runtimeSlice.ts, ui/src/lib/store/yjsSlice.ts, ui/src/pages/repo.tsx
Changes:
1. **results are now saved to yDoc** `.getMap("rootMap").get("resultMap")`, so that they sync with peers and are persisted
2. **runtime status is now saved to yDoc** `.getMap("rootMap").get("resultMap")`, so that peers share the exact runtime and share real-time status.
3. the **connection to the runtime kernel is moved behind Yjs**.
- **Detail**: the front end no longer directly connects to the runtime websocket. Instead, the Yjs server connects to runtime WS, receives and sets results in "resultMap", and sets runtime status in "runtimeMap".
- **Effect**: if you have some long-running code, **you can now safely close the page. The runtime will continue to run**, and results will continue to be populated (with a TODO caveat[1]). When you reopen the page, you can reload the exact …
=> feat: put runtime behind yjs

apps/api/src/yjs-runtime.ts, apps/ui/src/components/Sidebar.tsx, apps/ui/src/components/nodes/Code.tsx, apps/ui/src/components/nodes/utils.tsx, apps/ui/src/lib/store/canvasSlice.ts
- Support html output in pod output display, see screenshot below
- Fix exporting the repo in .ipynb format
- Fix import .ipynb notebook
- To-do:
- Tune the pod size based on `<img>` size
- Fix broken `Rich` pod export/import due to usage of yxml
- Fix "Raw JSON" export function
=> [UI] Fix export import after pr 467

compose/dev/.env.example, compose/dev/compose.yml, website/docs/4-developer/README.md
New docker-compose stack behavior:
1. remove xxx-node_modules volumes. We'll install directly on the mounted host dir.
2. add a setup service to run `pnpm install` and initialize DB.
As a result, the new development workflow:
```bash
docker compose up setup
docker compose up -d
```
=> [docker-compose] Add setup service to install node_modules and init db

compose/dev/compose.yml
Following up #475, add a docker volume `pnpm-store`, which serves two purposes:
1. Without it, pnpm install will throw an error. We had to use `pnpm config set store-dir ~/pnpm` to bypass the error, but this led to unusable `pnpm add/remove` afterward. Ref: https://github.com/pnpm/pnpm/issues/3952#issuecomment-1262136483
2. This volume is mounted to all service containers and will cache and speed up `pnpm install` and `pnpm add/remove`
=> add docker volume for pnpm-store

compose/dev/compose.yml, packages/prisma/package.json
This enhances the development workflow. Changes of `packages/.../src` will trigger change-watching and reloading in the use of the packages in `apps/...`.
=> setup: use index.ts as package's main for auto-watching

apps/yjs/src/yjs-blob.ts
- `Create New Project` in dashboard page throws `resultMap undefined` error and prevents page loading.
=> [backend] Fix new repo error from PR 485

apps/ui/src/components/nodes/Code.tsx, apps/ui/src/lib/store/podSlice.ts, apps/ui/src/lib/store/runtimeSlice.ts, apps/yjs/src/yjs-runtime.ts
- Reduce yjs sync via `resultMap.set()` method
- Fix  #483; very interesting solution from ChatGPT, while I didn't find its sources
- _Yjs is a CRDT framework that syncs JavaScript objects across multiple peers. However, it does not natively support all JavaScript types. The Date object is one of the types that Yjs does not natively support. When you try to sync a Date object, Yjs will only sync the reference to the object, not the actual date value. This is why you're seeing issues with syncing the "Date" field._
=> [Backend] Reduce resultMap sync frequency

compose/dev/compose.yml
Spawner docker container complains that `JWT_SECRET` is not found.
=> [Config] Add JWT_SECRET in spawner

apps/ui/src/lib/store/runtimeSlice.ts, apps/ui/src/lib/store/yjsSlice.ts
Now the active runtime should be set automatically when spawn/kill a runtime.
1. if a runtime is deleted, and if it was the active runtime, set the active runtime to `undefined`
2. if a runtime is added, and there's no active runtime, set the active runtime to the first runtime
#495 also tried to fix it.
=> properly update activeRuntime

apps/ui/src/components/Sidebar.tsx
When disconnected, don't show a `retry` button. The runtime connection is retried automatically every 1 second.
TODO: use exponential back-off for the retry time with a up-limit, e.g., 1s, 2s, 4s, 8s, 10s, 10s, 10s, ...
=> clean up runtime disconnected status/UI

apps/ui/src/components/Canvas.tsx, apps/ui/src/components/Sidebar.tsx, apps/ui/src/lib/store/canvasSlice.ts, apps/ui/src/lib/store/yjsSlice.ts
- Restore `node2children` and `buildNode2Children()` in `canvasSlice`
- Update `ToC` using `node2children`
- Fix issue #503
=> [UI] Update ToC when nodesMap change

apps/ui/src/components/Sidebar.tsx, apps/ui/src/components/nodes/utils.tsx
- Put the export functionality into one components
=> [UI] Unify export functions into one component

apps/ui/package.json, apps/ui/src/components/nodes/Rich.tsx, apps/ui/vite.config.ts, pnpm-lock.yaml
Vite [doesn't type-check](https://vitejs.dev/guide/features.html#transpile-only). Therefore, I'm adding [Vite-checker](https://github.com/fi3ework/vite-plugin-checker) to report compile errors (in both terminal and browser window).
=> add vite-checker

apps/ui/src/components/Canvas.tsx, apps/ui/src/components/MyMonaco.tsx, apps/ui/src/components/nodes/Code.tsx, apps/ui/src/components/nodes/Scope.tsx, apps/ui/src/lib/store/runtimeSlice.ts, apps/ui/src/pages/repo.tsx
Pass the apolloClient as a paramter instead.
Old:
```
apolloClient = useApolloClient()
setApolloClient(apolloClient)
...
yjsRun(id)
```
New:
```
apolloClient = useApolloClient()
yjsRun(id, apolloClient)
```
=> refactor: move apolloClient out of Zustand store

apps/api/package.json, apps/api/src/resolver_repo.ts, apps/api/src/run.ts, apps/api/src/server.ts, apps/api/src/typedefs.ts
Major Changes:
1. Remove code that operates the POD table, as the POD table was entirely deprecated.
Minors:
1. make codeiumAPIKey optional
2. extract server starting code to `run.ts`
=> refactor: remove deprecated resolver code

apps/file-backend/.gitignore, apps/file-backend/jest.config.js, apps/file-backend/package.json, apps/file-backend/src/run.ts, apps/file-backend/src/server.ts, apps/file-backend/tsconfig.json, compose/dev/compose.yml, pnpm-lock.yaml
This is a copy and cleanup of `api/` folder into `file-backend` folder. The file-backend is expected to
1. remove user authentication and
2. write to files instead of DB.
This PR initiates this effort.
=> init file-backend

apps/ui/src/components/Sidebar.tsx
This PR makes the TreeView controlled. All items are expanded, and toggle is disabled.
Some TODOs:
This PR also fixes a console error:
=> Make all treeview items expanded. Disable toggle.

apps/spawner/src/server.ts, compose/dev/compose.yml, compose/dev/nginx.conf
Regression caused by #526 changing container name from `yjs-server` to `yjs`, but forgot to update YJS_WS_URL
=> fix: yjs container name

apps/yjs/src/yjs-server.ts, apps/yjs/src/yjs-setupWS.ts
So that we can move yjs related setup functions to a package for code reuse between desktop-app and web-app in the following PRs.
=> refactor: extract out bindState and writeState

packages/ui/src/lib/store/canvasSlice.ts
Add proper typing instead of forced type casting. This will help catch Yjs-related errors early.
=> better typing for getNodesMap

apps/desktop-api/package.json, apps/spawner/src/run-docker.ts, apps/spawner/src/run-native.ts, apps/web-api/package.json, apps/web-api/src/server.ts, apps/web-yjs/src/run.ts, pnpm-lock.yaml
fix #536 
`require(dotenv)` isn't required, because we set ENV variables in compose.yaml, not loaded from `.env` file.
=> fix: remove dotenv

apps/desktop-api/src/server.ts
The desktop app (accessed from `desktop-ui` container, `localhost:3001`) now features a working file-backend. The files are saved to `/var/codepod/<repoID>/meta.json` (in the `desktop-ui` container).
The yjs blob was saved to `/var/yjs-blob/<repoID>` (in the desktop-yjs container) in #539.
=> implement desktop api file-backend saving

packages/ui/src/components/Canvas.tsx, packages/ui/src/components/CanvasContextMenu.tsx, packages/ui/src/components/MyMonaco.tsx, packages/ui/src/components/ShareProjDialog.tsx, packages/ui/src/components/Sidebar.tsx, packages/ui/src/components/nodes/Code.tsx, packages/ui/src/components/nodes/Rich.tsx, packages/ui/src/components/nodes/Scope.tsx, packages/ui/src/lib/store/canvasSlice.ts, packages/ui/src/lib/store/repoSlice.ts, packages/ui/src/lib/store/yjsSlice.ts, packages/ui/src/pages/repo.tsx
This is one of the efforts to make the component more **"(purely) functional"** by extracting states out. States are global variables that should be avoided when possible.
Removed states:
* `state.role`. Also removed all isGuest checks (replaced by a more functional state.editMode below).
* `state.user`. The user is only used in Awareness and is now passed as function parameter to `connectYjs` action.
* `state.repoLoaded`
Added states:
* `state.editMode: "edit" | "view"`. This could be set on-demand for web-ui when loading user authentication module.
Bug fix:
* In `Code.tsx` and `Rich.tsx`, the Wrap didn't use correct width/height when the role was in "Guest".
=> functional refactor & fix: remove state.role

packages/ui/src/components/Canvas.tsx, packages/ui/src/components/CanvasContextMenu.tsx, packages/ui/src/components/MyKBar.tsx, packages/ui/src/components/MyMonaco.tsx, packages/ui/src/components/ShareProjDialog.tsx, packages/ui/src/components/Sidebar.tsx, packages/ui/src/components/nodes/Code.tsx, packages/ui/src/components/nodes/Rich.tsx, packages/ui/src/components/nodes/Scope.tsx, packages/ui/src/components/nodes/extensions/link.tsx, packages/ui/src/components/nodes/utils.tsx, packages/ui/src/pages/repo.tsx
We don't need to report the error. The error will be reported by zustand. Just keep in mind that the store is only valid inside a <Repo> provided by `RepoContext.Provider`:
https://github.com/codepod-io/codepod/blob/79683dc6279b5086243dae5e155f33c1e32cb694/packages/ui/src/pages/repo.tsx#L451-L461
=> refactor: useStore! instead of checking for null

apps/desktop-api/src/server.ts, apps/desktop-yjs/src/yjs-blob.ts, compose/dev/compose.yml
Now desktop app's data is persisted in `/var/codepod`, which is mounted with docker volume `desktop-var-codepod`.
=> [desktop] save repo meta and yjsblob into desktop-var-codepod volume

packages/ui/src/lib/me.tsx, packages/ui/src/pages/dashboard.tsx, packages/ui/src/pages/repo.tsx
When `useMe` returns error, it means no user is signed in. This PR handles it instead of just throwing errors, e.g., Anonymous users should be able to see public repos.
=> fix: handle useMe null; add typing to useMe

packages/ui/src/components/MyMonaco.tsx, packages/ui/src/components/nodes/Rich.tsx, packages/ui/src/lib/store/canvasSlice.ts
Two fixes:
1. If `editMode==="view"`, the code/rich editors will be read-only
2. Newly created nodes will now sync across peers (previously not).
=> fix: support editor view mode; sync on new pods

apps/web-ui/src/lib/auth.tsx
The token shouldn't be printed.
=> chore: cleanup console log

api/src/cli.ts, api/src/run.ts, api/src/server.ts, api/src/yjs/yjs-blob.ts
Now the file structure is:
```
/path/to/repo
.codepod
yjs.bin
yjs.json
```
`yjs.bin` is the source-of-truth. `yjs-json` is for human-reading and backup purpose. It is never read-back to CodePod.
=> save a plain version of yjs content

.github/publish.yaml, api/package.json
This CI will
1. build the UI
2. build the API
3. run npm publish
It is triggered on new tags named `v*.*.*`
=> add CI for npm build & publish

.github/workflows/publish.yaml
This finally fixes the following CI npm auth error:
```
npm notice total files:   180                                     
npm notice 
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in to https://registry.npmjs.org/
npm ERR! need auth You need to authorize this machine using `npm adduser`
npm ERR! A complete log of this run can be found in: /home/runner/.npm/_logs/[202](https://github.com/codepod-io/codepod/actions/runs/6712487763/job/18242612030#step:7:203)3-10-31T21_27_17_803Z-debug-0.log
Error: Process completed with exit code 1.
```
=> add registry-url
