codepod-io/codepod

compose/dev/compose.yml

Fix this error for the prisma container:

fix prisma container "permission denied" issue

---

ui/src/components/repo/graph.js

Delete a code node without crashing. It also removes the record in database. 
TODO
- Add some easy-to-use UIs for deletion
- Improve when merging with the collaborative editing feature

fix(node_delete): check pod

---

ui/src/components/Canvas.tsx

Need to return something when pod===undefined; otherwise, the TS compiler will complain because the return type can be null.

fix custom node typing

---

compose/dev/compose.yml
ui/src/App.tsx
ui/src/components/Header.tsx
ui/src/components/Sidebar.tsx
ui/src/lib/fetch.tsx
ui/src/lib/runtime.tsx
ui/src/lib/store.tsx
ui/src/pages/profile.tsx
ui/src/pages/repo.tsx
ui/src/pages/repos.tsx

Improve UI (nav bar and canvas sidebar)

---

ui/src/components/Canvas.tsx
ui/src/components/CanvasContextMenu.tsx
ui/src/components/MyMonaco.tsx
ui/src/index.css
ui/src/lib/store.tsx

Toggle line numbers on or off by right click menu
close https://github.com/codepod-io/codepod/issues/37

Feat(UI): troggle line numbers in editors

---

ui/src/components/Canvas.tsx
ui/src/components/Toolbox.tsx
ui/src/components/canvas.style.js
ui/src/pages/repos/index.tsx

issue [74](https://github.com/codepod-io/codepod/issues/74)
1. move toggle button to outputbox
2. fix dashboard loading

feat: refactor output box

---

ui/src/components/Canvas.tsx

A tiny fix on sharing the pod name data by the yjs server in real-time
1. Sync the pod name of each pod right after the name changes. (ref: https://github.com/codepod-io/codepod/pull/129#issuecomment-1344641706)
2. Prohibit a guest user from modifying pod names in public repos (as the title in gray and immutable)
3. Disable dragging on the pod name title area (ref: https://github.com/codepod-io/codepod/pull/129#issuecomment-1344067882)

Feat: Sync pod name among users in real-time

---

ui/src/components/Canvas.tsx

Ref: https://github.com/codepod-io/codepod/pull/136#discussion_r1045447947

fix: call setPodPosition on drag stop

---

ui/src/components/Canvas.tsx

close https://github.com/codepod-io/codepod/issues/144

Fix: update all children node levels when dragging into a scope

---

ui/src/components/Canvas.tsx

#130 
I think the whole canvas is too complicated to modify UI style and handle business logic at the same time.
It would be better to provide a right sidebar like the design tool, so that when you select scope or node, you can modify their styles or attributes.
It may also need a designer. :)

fix(ui): remove bg and circle button on scope's bar

---

ui/src/components/nodes/Code.tsx

allow text selection in result block

---

ui/src/components/nodes/Scope.tsx

Make the scope's toolbar auto-hide as well.

use floating toolbar in scope pod

---

ui/src/components/nodes/Code.tsx
ui/src/lib/store/runtimeSlice.tsx

Now there's a "run chain" button to run a chain of pods connected with arrows.

feat: add run-chain to run a chain of pods

---

api/src/resolver_user.ts
api/src/typedefs.ts
ui/package.json
ui/src/lib/auth.tsx
ui/src/pages/login.tsx
ui/src/pages/repos.tsx
ui/src/pages/signup.tsx
ui/yarn.lock

If the user doesn't log in, a Guest user will be created automatically. The Guest user can create a project and start using Codepod right away. There will be prompt noticing users that they are using guest accounts.
Once the user signup an account and log in, the projects created under the Guest user won't be transferred.

feat: add anonymous Guest user

---

api/src/spawner-k8s.ts

The k8s container name was something like this:
```
runtime-k8s-guest-9l2k0c0m2hk9cweofbao-17tz71kgx0dznjs5kl7j-kernel
```
The k8s container name has to be no more than 63 characters to be valid. Otherwise, the following error will be thrown:
```
ERROR Deployment.apps
"runtime-k8s-guest-9l2k0c0m2hk9cweofbao-17tz71kgx0dznjs5kl7j-deployment" is
invalid: spec.template.spec.containers[0].name: Invalid value:
"runtime-k8s-guest-9l2k0c0m2hk9cweofbao-17tz71kgx0dznjs5kl7j-kernel": must be no
more than 63 characters
```
This PR simplifies the name to:
```
rt-9l2k0c0m2hk9cweofbao-17tz71kgx0dznjs5kl7j-kernel
```

simplify k8s container names

---

ui/src/App.tsx
ui/src/components/nodes/Rich.tsx
ui/src/lib/store/canvasSlice.tsx

Do not use `remirror-emotion` styling. The error was mentioned in https://github.com/codepod-io/codepod/pull/160#issuecomment-1362211216

fix: remirror emotion error

---

ui/src/components/nodes/Rich.tsx

The link works in many ways:
1. if you type some URL such as `google.com`, it will automatically converted into a link
2. paste a link or a link-with-text into the editor will create a link
3. select some text and click the `add link` button
To edit a link, click on the link, there will be two buttons: `edit link` and `remove link`.
To open the link, right click and select "open link in new tab".
Reference: https://remirror.io/docs/extensions/link-extension/

feat: use remirror link extension

---

ui/src/lib/auth.tsx

fix: getAuthHeaders typing

---

ui/package.json
ui/src/lib/store/canvasSlice.tsx
ui/src/lib/store/settingSlice.tsx
ui/yarn.lock

Now use rectangle collision instead of circle collision in #245 
Reference: https://observablehq.com/@roblallier/rectangle-collision-force

use rectangle collision in d3-force auto layout

---

ui/src/lib/store/canvasSlice.tsx

Forgot to check in one line of change in #271

fix YMap import

---

ui/src/lib/store/canvasSlice.tsx

The previous auto-layout will keep the scope's top-left corner position. For example, the move of pod "2" right:
will result in:
Now, we'll keep the position of pods, but wrap the scope around. After the move, now the extra space is not there:

fix: scope offset

---

ui/src/components/nodes/Code.tsx

fix: error for displaying result when node is removed

---

ui/src/components/nodes/Code.tsx
ui/src/lib/parser.tsx
ui/src/lib/store/runtimeSlice.tsx

Now python Class is supported in scoped runtime.

feat: add scoped Class

---

api/src/resolver_repo.ts
api/src/typedefs.ts
ui/src/components/Header.tsx
ui/src/pages/repo.tsx

Make a copy of the current repo and navigate to the copied repo (untitled) in-place. 
Because the only difference is the repo id (URL), so it looks exactly the same after clicking on the button, just keep an eye on the address in your browser.

Feat: Fork a Repo

---

ui/src/components/nodes/Rich.tsx

refine editor toolbar appearance

---

website/docs/4-developer/README.md

Companion PR for #348. Also did a prettifier formatting for the lists.

update docs for changing port to :8080

---

ui/src/pages/repos.tsx

from:
no confirm dialog after use click delete icon of a repo on the repo list
to:

fix: [UI] add confirm delete repo dialog

---

ui/src/components/nodes/Rich.tsx

The slash command is messing up with links. Remove it for now. The slash command should be added back when it doesn't interfere with other features.
Also support `.dev` in auto-link.
fix #384

fix: add .dev tlds for link; remove /table slash cmd

---

ui/src/components/nodes/extensions/codepodSync.ts

Regression bug introduced by #396

fix: markdown gen place

---

ui/src/App.css
ui/src/components/nodes/Rich.tsx
ui/src/lib/auth.tsx

Fix #404 
Also contains some minor code cleanups & formatting

fix: do not attach guestToken when signup/login

---

ui/src/components/nodes/Rich.tsx

fix: remove drag handle on leaving Rich pod

---

ui/src/App.tsx
ui/src/pages/dashboard.tsx

chore: rename repos.tsx to dashboard.tsx

---

api/package.json
api/src/yjs-server.ts
api/src/yjs-setupWS.ts
api/yarn.lock
compose/dev/compose.yml
compose/dev/nginx.conf

Before: Run vanilla `npx y-websocket` for a yjs WS server.
After: Embed the source code into `api/` folder for future customized yjs server integration.

include yjs server code in api/ folder

---

api/prisma/migrations/20230804210253_remove_guest/migration.sql
api/prisma/schema.prisma
api/src/resolver_user.ts
api/src/typedefs.ts
ui/src/lib/auth.tsx
ui/src/pages/dashboard.tsx
website/docs/3-manual/README.md

#242 introduced an anonymous guest user feature to allow users to try out CodePod without signing in.
However, the guest token expires in 30 days. After the token expired, there's no way to log in again. This isn't a good design. After the token expires, the app is stuck at the dashboard loading. The Anonymous feature should be done more properly.
This PR temporarily removes this feature.

fix: remove anonymous guest user

---

ui/src/lib/store/canvasSlice.tsx

Following #452, support copy scopes.

feat: support copying scopes

---

ui/src/lib/store/runtimeSlice.ts

Fix issue mentioned in https://github.com/codepod-io/codepod/pull/440#pullrequestreview-1585765188

fix: runtime children computation

---

apps/ui/index.html
compose/dev/nginx.conf

A few forgotten commits for #468.

chore: Vite leftover

---

apps/ui/package.json
compose/dev/compose.yml

After https://github.com/codepod-io/codepod/pull/467, the UI container may not start
Besides, too many changes. My work on rewriting copy/paste and import/export almost in vain...Too many conflicts to resolve, I need to clean the branch and transfer code by hand. Is there any update on dev manual to describe how to run and maintain the project now?

[Fix] Auto-completion dependencies

---

apps/spawner/src/server.ts

There was a buggy behavior: the first time spawning a runtime, it would not show up. It's because we tried to add the runtime before the provider was ready, thus the adding was dropped.
This PR fixes it by await after the provider is synced.

fix: await provider.synced before adding runtime

---

apps/spawner/src/server.ts

This is also in Sen's https://github.com/codepod-io/codepod/pull/495#discussion_r1310959081

fix: delete runtime

---

apps/spawner/src/server.ts

Prevent unauthorized users from accessing spawner APIs. This PR only check for if user is logged in.
TODO:

add basic auth to spawner

---

apps/ui/src/pages/dashboard.tsx

do not auto-jump to login page

---

packages/ui/src/components/Sidebar.tsx
packages/ui/src/lib/store/settingSlice.ts
packages/ui/src/pages/repo.tsx

Same as #523, resolving conflicts.

[UI] add settings for sidebar position

---

apps/web-ui/src/App.tsx

Regression caused by #524. Need to first check `isSignedIn` and then in another component, call the `useMe` hook.

fix: profile button

---

apps/desktop-yjs/.gitignore
apps/desktop-yjs/package.json
apps/desktop-yjs/src/run.ts
apps/desktop-yjs/src/yjs-blob.ts
apps/desktop-yjs/src/yjs-server.ts
apps/desktop-yjs/tsconfig.json
compose/dev/compose.yml
pnpm-lock.yaml

This is a un-authenticated yjs server for desktop-app. Status of the desktop app:

add desktop-yjs

---

apps/web-ui/src/App.tsx
packages/ui/src/lib/store/repoSlice.ts
packages/ui/src/pages/dashboard.tsx

* desktop app won't require login to view dashboard
* set GetDashboardRepos query to always fetch from the API, solving some refreshing issue.

split dashboard user loading for web and desktop

---

packages/ui/src/components/Canvas.tsx
packages/ui/src/lib/store/yjsSlice.ts

1. move nodesMap.observe from Canvas.tsx to `provider.once("synced", ...)` in yjsSlice.tsx
2. add edgesMap.observe

move yjs observers to provider.once("synced")

---

apps/desktop-api/src/server.ts

star/unstar now work on desktop app.

[desktop] make star/unstar work

---

apps/web-yjs/src/yjs-server.ts

Now anonymous user has access to YDoc of public repos.
One caveat: the sync status is always "uploading".
TODOs:

allow read-only access to YDoc to anonymous users

---

BUILD.md
api/package.json
api/src/cli.ts
api/src/server.ts
api/src/spawner/trpc.ts
ui/src/App.tsx

Now the runtime works for an installed binary executable from npm.
```
> npm install -g codepod
> codepod /path/to/repo
```
Npm package is at https://www.npmjs.com/package/codepod

fix npm cli; parameterize yjs port in trpc router

---

README.md
api/src/yjs/yjs-blob.ts

Instead of #572's files:
```
/path/to/repo
.codepod
yjs.bin
yjs.json
```
Now use
```
/path/to/repo
codepod.bin
codepod.json
```

save to codepod.json and codepod.bin
